name: Build
on:
#  push:
#    branches:
#      - main
  workflow_dispatch:  # Ermöglicht manuelle Auslöser
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  build_ios_without_signing_tvos:
    name: Build Expo (tvOS) Without Signing
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install sponge
        run: brew install sponge
      - name: Setup
        uses: ./.github/actions/prebuild
        with:
          is-tv: 'true'
          platform: "ios"
      - name: Build Expo IPA
        run: |
          cd ios
          xcodebuild -scheme reacttube -workspace reacttube.xcworkspace -configuration release archive -archivePath reacttube.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
          ../scripts/xcarchive_to_ipa.sh reacttube.xcarchive
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: tvos_ipa
          path: ios/*.ipa
      - name: Upload IPA to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ios/*.ipa

